version: '3.9'
services:
    db:
        container_name: db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: ${TYPEORM_DATABASE}
            POSTGRES_USER: ${TYPEORM_USERNAME}
            POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
        ports:
            - ${TYPEORM_PORT}:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
volumes:
    pg_data: